### ISSUE TITLE
Unable to upload this file to the OAP Dashboard

### ISSUE THREAD

**Issue by eugeneburger** [NOAA-PMEL/OAPDashboard#13]
I was unable to upload [this Smartfin temperature](https://github.com/NOAA-PMEL/OAPDashboard/blob/master/UploadDashboard/test-data/3028_070100.csv) data file to the OAP Dashboard - not sure what the constraint was in the file format.

**Comment by lkamb** [comment]
This is not a format we understand.  There are several lines of metadata (masquerading as rows) at the start of the file, and there are no column headers.

**Comment by lkamb** [comment]
It could be uploaded as type "other"
