### ISSUE TITLE
Metadata integration: Ensure the Dashboard is updated when metadata are updated

### ISSUE THREAD

**Issue by eugeneburger** [NOAA-PMEL/OAPDashboard#15]
When the user saves metadata, this should be reflected in the dashboard. Add a (metadata) reload button that become active, or some indication that the metadata has been updated.

**Comment by lkamb** [comment]
With the inclusion of the metadata editor tool into the Dashboard, is this still relevant?   When the user saves, there is a notice that that the metadata has been updated, and when the user returns to the dataset list page, the metadata timestamp reflects the latest update time.
