### ISSUE TITLE
Not all metadata are saved

### ISSUE THREAD

**Issue by eugeneburger** [NOAA-PMEL/OAPDashboard#18]
I edited a field in the "Data submitter section" and the "PCO2A" sections and clicked done. The information in the PCO2A section was not saved.

**Comment by lkamb** [comment]
This is technically a bug in the MetadataEditor.  The pCO2a gets saved as simply "pCO2" and when reloaded, comes back as a generic variable.  Try it in the stand-alone MetadataEditor.
