### ISSUE TITLE
Allow relative pathnames in config file

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/OAPDashboard#2]
All the full-path filenames in OAPUploadDashboard.properties is a pain when they are all in the same config subdirectory as OAPUploadDashboard.properties 
Change so that filenames without a leading slash are relative to the directory containing OAPUploadDashboard.properties.

**Comment by lkamb** [comment]
I've committed changes to DashboardConfigStore.java to handle all file path-type properties to support path names that are relative to the directory that contains the config properties file.  This includes other properties files typically in the same directory, as well as paths to the various svn-backed content directories.
