### ISSUE TITLE
Incorrect authentication status

### ISSUE THREAD

**Issue by eugeneburger** [NOAA-PMEL/OAPDashboard#24]
When viewing data in the previous plots, the user status is shown as "Not logged in", en though the user is authenticated.
<img width="1225" alt="Screen Shot 2020-07-18 at 02 08 17" src="https://user-images.githubusercontent.com/16405410/87849244-de1ab600-c89b-11ea-924f-9fd1f3f7eeae.png">

**Comment by lkamb** [comment]
fixed in 2f3e41f
