### ISSUE TITLE
List of authors for citation purposes needs to be a required element

### ISSUE THREAD

**Issue by lqjiang** [NOAA-PMEL/OAPDashboard#26]
This metadata element is required in order to properly create a data citation at NCEI. Please enforce the collection of this information.

A suggested input formulated by using the current list of Investigators will be great.

Thanks,

Liqing

**Comment by lkamb** [comment]
This is an [OAPMetadataEditor](https://github.com/NOAA-PMEL/OAPMetadataEditor) issue.
See #[87](https://github.com/NOAA-PMEL/OAPMetadataEditor/issues/87).
Closing this.
