### ISSUE TITLE
Required elements for a parameters

### ISSUE THREAD

**Issue by lqjiang** [NOAA-PMEL/OAPDashboard#27]
This is more of a question. 

For example, "Variable abbreviation" is required for DIC. What if a user is submitting a data set without DIC at all? Basically, can we make sure this element is only enforced, when such a parameter (in this case, DIC) is being input. If they do not have this parameter at all, it will not serve as a roadblock for their submission?

Has this already been the case? If so, please just close this request for me. 

Liqing

**Comment by lkamb** [comment]
Yes, the "Big 5" have to be handled differently.
