### ISSUE TITLE
Naming of the generated XML files

### ISSUE THREAD

**Issue by lqjiang** [NOAA-PMEL/OAPDashboard#28]
Hi Linus,

To reduce confusion, would you please consider doing the below for us?
- Name the OADS.xml file using the format of SubmissionID_metadata.xml. 
- Name the OCADS.xml file using the format of SubmissionID_machineUse.xml.

Many thanks!

**Comment by eugeneburger** [comment]
Thank you, Liqing - tied up with a demo today, but acknowledge receipt.

**Comment by lkamb** [comment]
Completed in 1767ed95cb6d1baaab1f9df4f7e79491c139512b
