### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by lqjiang** [NOAA-PMEL/OAPDashboard#40]
Hi Linus,

Will it be possible to ensure that only UTF-8 encoded special characters can be input to the metadata editor?

Right now, we receive lots of non-UTF-8 special characters that often break up our data flow. We would have to manually remove them. It can be a very laborious process sometimes. 

Many thanks!

Liqing

**Comment by lkamb** [comment]
Yes, I have had troubles with non-UTF characters as well.

Can you give me an example of one or more that gave you all trouble?  Either the output XML or the SDIS ID, or anything else that would allow me to identify it so I can test/experiment.

Thanks.

**Comment by lkamb** [comment]
A work-around was implemented in the [excel2oap](https://github.com/NOAA-PMEL/excel2oap) project and pulled into the [OAPMetadataEditor](https://github.com/NOAA-PMEL/OAPMetadataEditor) in commit https://github.com/NOAA-PMEL/OAPMetadataEditor/commit/790f40c1b6d1ebb0cdef3172608e89b8b997e5bd .
The work-around checks the OS of the client machine uploading the spreadsheet and sets the character set to "windows-1258" for Windows machines.

This was only seemed to be happening for CSV files uploaded from Windows machines.
