### ISSUE TITLE
Can not replace an uploaded date file

### ISSUE THREAD

**Issue by lqjiang** [NOAA-PMEL/OAPDashboard#56]
I was trying to update my data file with a new version for submission ID: BF3W7YTSC. After I selected the file, clicked the "upload" button, I saw a pop-up window saying "Confirm: replace uploaded file nc.zip with a new version?". Unfortunately, after I clicked the "Yes" button on the pop up window, it simply took me back to the below window, instead of actually doing the work of uploading and replacing the file.

I tried different browsers and the issue persisted.

**Comment by lkamb** [comment]
The replacement file is actually uploaded, but the file list display is not being updated.  Reloading the page will show the replacement file and new upload timestamp.

I will force a refresh of the dataset listing.

**Comment by lkamb** [comment]
fixed in [03b8984](https://github.com/NOAA-PMEL/OAPDashboard/commit/03b89840fd6c99d1a568ce84e12b0163816e77c1)
