### ISSUE TITLE
Need a new button for the OA variables

### ISSUE THREAD

**Issue by lqjiang** [NOAA-PMEL/OAPDashboard#58]
For the 5 OA variables, DIC, TA, pH, fCO2A, and fCO2D, would you please add a new button called "Clear xxx", next to "SAVE xxx". 

For example, I just created a new package using the clone function. My old package had some parameters like fCO2A that my new package does not have, now I have to go through each of the child elements of the fCO2A to delete them. It would be great to have an extra button called "Clear fCO2A" so that I can clear everything about this variable quickly.

Thanks,

Liqing

**Comment by lqjiang** [comment]
As a matter of fact, the below two fields:
- "Details about the Observation" and 
- "Measured or Calculated" 
can not be manually cleared, because they are dropdown menus. I end up stuck with an extra variable that my data package does not have.

**Comment by lkamb** [comment]
Completed in [OAPMetadataEditor](https://github.com/NOAA-PMEL/OAPMetadataEditor) project commit f5bf9e0307c98bb099a674bbdf806ff07df0a2f6
