### ISSUE TITLE
The bar with 3 buttons: Preview, Download, and Save

### ISSUE THREAD

**Issue by lqjiang** [NOAA-PMEL/OAPDashboard#61]
Please keep them separate:

1. "Preview" should be a separate button. 

2. Download should be a separate button. Please replace "Download" with "Download metadata as an XML file"

3. Delete the "Save" button (see the other Github issue I created). 

4. Replace the instructions of "Upload OADS Metadata File (XML, Excel, or CSV)" with "Populate the metadata using an XML, Excel, or CSV file". 

5. Do we really need the "Clear All" button? It can be very dangerous, erasing everything unexpected.

**Comment by lkamb** [comment]
Partially addressed (visual separation) by [OAPMetadata](https://github.com/NOAA-PMEL/OAPMetadataEditor) commit [850e91e](https://github.com/NOAA-PMEL/OAPMetadataEditor/commit/850e91e13e586efed6104c431ff517cce86b1534)

**Comment by lkamb** [comment]
The "Clear All" should prompt with a warning if there is any content that will be cleared.

**Comment by lkamb** [comment]
Force "Clear All" to always show warning prompt. Previously, under certain circumstances, the "Clear All" could clear all data without prompting.  Addressed in [OAPMetadata](https://github.com/NOAA-PMEL/OAPMetadataEditor) commit [b70ae46](https://github.com/NOAA-PMEL/OAPMetadataEditor/commit/b70ae469b00b0d5de2b388fbbae08696336864a9).
