### ISSUE TITLE
Name of the SDIS

### ISSUE THREAD

**Issue by lqjiang** [NOAA-PMEL/OAPDashboard#66]
Right now, it is not consistent:

- Before logging in, it is called "OAP Scientific Data Information System" 
- After logged in, it is called "OAP Science Data Information System"
- A lot of the times, it was referred to as "Scientific Data Integration System" (my preference)

In our recent OCADS paper, it is called "Scientific Data Information System". I assume this is the right way to call it? If so, please update the typos in the other places. 

Thanks,

Liqing

**Comment by lkamb** [comment]
Out of these choices, my preference would be for "Science Data Information System," but as it was published as "Scientific Data Information System," I have made that change in the various places I could find it as "Science Data Information System."  I am in the process of rolling this out to production.

I have not found any references to "Scientific Data Integration System."  If you know of any, or find any, please let me know.

**Comment by lkamb** [comment]
fixed in dc09412dd99ba23e1ac689f49e968b026b756512
