### ISSUE TITLE
Add "Save without Checking" button to column identification

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/OAPDashboard#7]
Adding the button, which would go through the process of saving the column types and user-specific keys-to-types, but not do any bounds or sanity checking, would allow users to save a partial progress on identifying columns and allow them to return later to finish.  Would help folks that have to leave part way through only to find later the page has timed out and they have to start all over.

**Comment by lkamb** [comment]
closed via commit [2b8f21f](https://github.com/NOAA-PMEL/OAPDashboard/commit/2b8f21f1a8432cc877bc4e6e711017c88d361a6b)
