### ISSUE TITLE
Trap session timeout errors so a user can re-login without having to reload the whole app

### ISSUE THREAD

**Issue by lkamb** [NOAA-PMEL/OAPDashboard#9]
If a user is in the middle of an activity such as identifying dataset column data types and their session expires, they currently will get a popup error message showing the raw HTML of the login page which indicates they must reload the application, thereby losing any work they have done.  It would be preferable on session timeout to present a login popup instead allowing them to refresh their session and continue working.

A "Save" button (see issue #7 ) is a good pro-active measure to allow users to save intermediate results if they know they are going away, but it doesn't solve the issue of a session timeout forcing a complete reload of the application.   For example if the session has timed out before the Save button is pressed.

**Comment by lkamb** [comment]
This has been implemented.  A popup dialog is presented, leaving the application in its current state.  The attempted operation that triggered the need to login again is aborted and has to be re-executed.

**Comment by rohangupta029** [comment]
sir after clonning the site and opening it. it does'nt show in my login id. in login id it only show 0 users online

**Comment by lkamb** [comment]
I'm not sure I understand.  Could you please provide a little more information.
